#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F 1
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F 2
#define HEAL_LOCATION_PETALBURG_CITY 3
#define HEAL_LOCATION_SLATEPORT_CITY 4
#define HEAL_LOCATION_MAUVILLE_CITY 5
#define HEAL_LOCATION_RUSTBORO_CITY 6
#define HEAL_LOCATION_FORTREE_CITY 7
#define HEAL_LOCATION_LILYCOVE_CITY 8
#define HEAL_LOCATION_MOSSDEEP_CITY 9
#define HEAL_LOCATION_SOOTOPOLIS_CITY 10
#define HEAL_LOCATION_EVER_GRANDE_CITY 11
#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE 12
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE 13
#define HEAL_LOCATION_OLDALE_TOWN 14
#define HEAL_LOCATION_DEWFORD_TOWN 15
#define HEAL_LOCATION_LAVARIDGE_TOWN 16
#define HEAL_LOCATION_FALLARBOR_TOWN 17
#define HEAL_LOCATION_VERDANTURF_TOWN 18
#define HEAL_LOCATION_PACIFIDLOG_TOWN 19
#define HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE 20
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 21
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 22
#define HEAL_LOCATION_COUNT 23
#define HEAL_LOCATION_ONE_TOWN 24
#define HEAL_LOCATION_TWO_CITY 25
#define HEAL_LOCATION_THREE_CITY 26
#define HEAL_LOCATION_FOUR_TOWN 27
#define HEAL_LOCATION_FIVE_TOWN 28
#define HEAL_LOCATION_SIX_TOWN 29
#define HEAL_LOCATION_SEVEN_CITY 30
#define HEAL_LOCATION_EIGHT_TOWN 31
#define HEAL_LOCATION_NINE_TOWN 32
#define HEAL_LOCATION_TEN_CITY 33
#define HEAL_LOCATION_ELEVEN_CITY 34
#define HEAL_LOCATION_TWELVE_TOWN 35
#define HEAL_LOCATION_THIRTEEN_TOWN 36
#define HEAL_LOCATION_FOURTEEN_TOWN 37
#define HEAL_LOCATION_FIFTEEN_CITY 38
#define HEAL_LOCATION_SIXTEEN_TOWN 39

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
